runtime: python312
service: adelino-front

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
  # 0. Manifesto PWA com MIME correto
  - url: /manifest\.webmanifest
    static_files: dist/adelino-front/manifest.webmanifest
    upload: dist/adelino-front/manifest.webmanifest
    mime_type: application/manifest+json
    secure: always

  # 1. Arquivos .wasm com o MIME type explicitamente forçado
  - url: /(.*\.wasm)$
    static_files: dist/adelino-front/\1
    upload: dist/adelino-front/.*\.wasm
    mime_type: application/wasm
    secure: always

  # 2. Demais arquivos estáticos
  - url: /(.*\.(ico|gif|png|ttf|woff|woff2|eot|svg|jpg|jpeg|css|js)(|\.map))$
    static_files: dist/adelino-front/\1
    upload: dist/adelino-front/.*\.(ico|gif|png|ttf|woff|woff2|eot|svg|jpg|jpeg|css|js)(|\.map)
    secure: always

  # 3. Roteamento SPA: qualquer outro caminho → index.html
  - url: /.*
    static_files: dist/adelino-front/index.html
    upload: dist/adelino-front/index.html
    secure: always
